# syntax - https://github.com/redhat-plumbers-in-action/devel-freezer#policy
---

policy:
  - tags: ['alpha', 'beta']
    feedback:
      frozen-state: |
        ðŸ¥¶ We are currently in ...
        ðŸ™ Please ...
      unfreeze-state: |
        ðŸ˜Ž We are no longer in ...

  # Suport for regular expressions
  - tags: ['^\S*-rc\d$']
    feedback:
      frozen-state: |
        > [!IMPORTANT]
        > We are currently in a development freeze phase.
        > Please ...
      unfreeze-state: |
        > [!NOTE]
        > We had successfully released a new major release.
        > We are no longer in a development freeze phase.
