---

name: Gather Pull Request Metadata

on:
  pull_request:
    branches: [ main ]

env:
  PULL_REQUEST_METADATA_DIR: pull_request
  PULL_REQUEST_METADATA_FILE: metadata

permissions:
  contents: read

jobs:
  gather-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Store PR number in file
        run: |
          mkdir -p ./${{ env.PULL_REQUEST_METADATA_DIR }}
          echo ${{ github.event.number }} > ./${{ env.PULL_REQUEST_METADATA_DIR }}/${{ env.PULL_REQUEST_METADATA_FILE }}

      - name: Upload Pull Request Metadata artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PULL_REQUEST_METADATA_FILE }}
          path: ${{ env.PULL_REQUEST_METADATA_DIR }}
          retention-days: 1

...
